name: Rust Clippy Check

on:
  push:
    paths:
      - 'screentap-app/src-tauri/**'
  pull_request:
    paths:
      - 'screentap-app/src-tauri/**'

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - name: Check with Clippy
      uses: LoliGothick/clippy-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        working-directory: screentap-app/src-tauri
