name: Rust Clippy Check

on:
  push:
    paths:
      - 'screentap-app/src-tauri/**'
  pull_request:
    paths:
      - 'screentap-app/src-tauri/**'

jobs:
  clippy:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - name: Clippy
      run: cargo clippy -- -D warnings
      working-directory: ./screentap-app/src-tauri/

    - name: Tests
      run: cargo test
      working-directory: ./screentap-app/src-tauri/
