name: Rust Clippy Check

on:
  push:
    paths:
      - 'screentap-app/src-tauri/**'
  pull_request:
    paths:
      - 'screentap-app/src-tauri/**'

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true

    - name: Build
      run: cargo build
      working-directory: ./screentap-app/src-tauri/

    - name: Check with Clippy
      uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workdir: screentap-app/src-tauri
        clippy_flags: -- -Dwarnings
        fail_on_error: true
